---
- hosts: nodes
  remote_user: ansible
  become: yes

  tasks:
   - name: install httpd
     yum:
      name: httpd
      state: present
   - name: run service httpd
     service:
         name: httpd
         state: started
   - name: create index.html
     copy:
        dest: /var/www/html/index.html
        content: Welcome to my web server
   - name: open port 80
     firewalld:
         port: 80/tcp
         permanent: true
         state: enabled
   - name: open port 443
     firewalld:
         port: 443/tcp
         permanent: true
         state: enabled
...
